#!/usr/bin/env bash
# Adding Server Header

sudo apt-get -y update 
sudo apt-get -y upgrade 
sudo apt-get -y install haproxy

str1="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_back\n\n"
str2="backend custom_back\n\tbalance roundrobin\n\tserver web-01 3.80.127.172:80 check\n\tserver web-02 54.86.53.211:80 check"

sudo echo -e $str1 | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e $str2 | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart