#!/usr/bin/env bash
#Creates file display message indefinetly, display diff message on SIGTERM
echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid' SIGTERM
trap 'rm /var/run/holbertonscript.pid' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done