#!/usr/bin/env bash
#Displays Holberton School 10 times, after 9th display Hi using while loop
i=1
while [ $i -lt 11 ]
do
    if [[ "$i" == "10" ]];
    then 
        echo Hi
    fi
    echo Holberton School
    ((i++))
done