#!/usr/bin/env bash
#Displays Holberton School 10 times, after 9th display Hi using while loop
i=0
while [ $i -lt 10 ]
do
    if [[ "$i" == "9" ]];
    then 
        echo Hi
    fi
    echo Holberton School
    ((i++))
done