#!/usr/bin/env bash
#Gives you information about the holbertonschool file.
#If the file exists it gives message if not exist gives different message 
file="holbertonschool"
if [ -f "$file" -o -b "$file" -o -c "$file" -o -d "$file" ]; then
        echo "$file file exists"
        if [ -f "$file" ]; then
                if [ "$(wc -c $file)" != "0" ]; then
                        echo "$file file is not empty" 
                else
                        echo "$file is empty"
                fi
                echo "$file is a regular file"
        else
                echo "$file file is not empty"
        fi
else
        echo "$file does not exist"
fi
